apiVersion: v1
kind: Service
metadata:
  name: freshmart-service
  namespace: cloudforge

spec:
  type: LoadBalancer

  selector:
    app: freshmart

  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
